### ISSUE TITLE
Shortcut Keys Do Not Work in 1.1.2

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended#11]
Upgraded to the latest version, and now none of the shortcut keys seem to work. I tried reinstalling both Sumblime and the org extended package, and also had a look at the latest commit, but the cause was not apparent.

**Comment by ihdavids** [comment]
Looks like there is a bug.
I will fix tomorrow

**Comment by Anti-Distinctlyminty** [comment]
Extra info: It seems to have effected all shortcut keys in all contexts. I noticed that shortcut keys weren't working when syntax was set to Python either.

**Comment by ihdavids** [comment]
Can you press ctrl+ backtick to bring up the sublime console and copy out any errors you see in there.

**Comment by ihdavids** [comment]
I cannot duplicate your issue so I need that output to try to track this down.
I did find one major issue with restarts that I have sorted out in 1.1.3 already.

**Comment by ihdavids** [comment]
1.1.3 is posted. I hacked a fix in there for the other issue. I got fancy when adding the DEADLINE and active timestamp inserting commands. (Since they are really the same command as the SCHEDULED command). That seems to have bitten me. I patched it but I really need to rejigger that so it can't cause me problems going forward.

Let me know if 1.1.3 fixes your issue or if we still have a problem here you and I need to dig into.
In general it would help if you popped open the log console for sublime and looked for any callstacks you see in there. (errors) and pasted all the output into the issues. Hopefully I won't make a broken release like this in the future but I am sure you will find bugs (assuming you continue to use this package) and if you do, I can solve them faster if I have a callstack in the issue report.

**Comment by Anti-Distinctlyminty** [comment]
1.1.3 Seems to have fixed the issue - thank you.
And yes, in the future I'll look into the callstacks myself to see if I can figure out what is going on. (I would've looked in there sooner but the key combination is bound to something else on my machine).
Thanks again,

**Comment by ihdavids** [comment]
Note 
As I have been working today I have found a couple bugs with ranged timestamps not showing up for active timestamps and closed scheduled items showing up in the week view after they are closed.

I have fixes for those and they will be in 1.1.4 tonight.
I consume the package version on my work machines which hopefully means I find my own issues faster.

**Comment by ihdavids** [comment]
I really need to build some regression tests for this stuff as it seems a few people are now using it.

**Comment by Anti-Distinctlyminty** [comment]
Yes, they are life savers in the long run, so it's worth the investment. 
I showed this to my colleague and he's very eager to start using it, so an additional user is on the way :)

**Comment by ihdavids** [comment]
I got a couple of reports right away about 1.1.2. I was surprised that there are some active users that would notice problems quickly. Within minutes of release even. It was quite encouraging actually.

I hope the package helps you as it has helped me. Thats about all I can hope for.
