### ISSUE TITLE
Linux/Ubuntu-Support

### ISSUE THREAD

**Issue by dcbx** [ihdavids/orgextended#23]
Hey there! First of all I'd like to say, how much I appreciate your project! While searching for an alternative for todo.txt (w/ multi line capability) I stumbled upon org-mode, and instantly loved the concept! Learning the key bindings of emacs on the other hand.. it's not that I don't want to, but I'm really used to writing my notes, code etc. in sublime and it's just part of my daily workflow..
Anyway, coming to my problem. I have to apologize for this rather broad issue description, but I want to sort things out, before I'm trying to test several different settings.
I have an up-to-date install of sublime 3 on my work machine running Ubuntu 20.04 (Wayland). I have your package installed and set up, but it just works kind of odd: e.g. <tab> cycles through folding, but <ctrl> + <return> does nothing. I can open agenda but every task shows multiple times. I can't insert timestamps. The list goes on.
So I just wanted to reach out first, to ask, if that's kind of known, maybe some issue with Wayland, and of course if supporting other OS is something you're up to?
Kind regards, Daniel.

**Comment by ihdavids** [comment]
Great! 
I am glad the project is of interest to you.

Short answer.... I dont know. I havent been running it on linux in a bit. I will check and get back to you.

It is certainly supposed to be working and did at one time.

**Comment by ihdavids** [comment]
You can help me with concrete examples of your problems. Start with the most pressing and I will endeavour to help where I can.

**Comment by ihdavids** [comment]
Hmmm, I just fired it up on ST4 running on 20.04 focal and I am not seeing anything obvious.

NOTE: Folding is done using the tab and shift tab key in a context sensitive way since that is the way orgmode does it. IF it folds in an odd way that means I have a bug (probably) The folding system works off the parsed org files and it CAN get out of sync. If you unfold first then save the file things should get back to normal. More importantly, please let me know what you were doing so I can try to fix that.

I will continue to play around and try ST3 etc but I could use some more guidance of what you are seeing. I really haven't tested the full gamut of options on linux and should take some time to do that in the next little while.

NOTE: My keybindings leave something to be desired. If you would like to suggest keybindings or even fire up a PR for some improvements I am happy to try to accomodate. I am mostly working on a mac and a windows box these days, but even the mac is lagging and doesn't have a good default scheme, especially with all the newer options I have been adding.

I am happy to have help as well so if there are things that annoy you and you want / can contribute (even the docs) please feel free to help.

**Comment by ihdavids** [comment]
There is a discord community I have tossed up (OrgExtended) feel free to join if you would like.

**Comment by ihdavids** [comment]
I just ran against ST3. I am not seeing anything super odd. I could use some more guidance into what you are struggling with.
OrgExtended is a big complex monster and it certainly has it's challenges.

Have you opened up your Ctrl-~ console and looked for any exceptions that might be being generated during startup?
I can give you an option for turning on verbose logging so we can see if there is anything the package is encountering and hiding from us.

**Comment by dcbx** [comment]
Oh, wow! I wasn't expecting your response THAT fast! Thanks!
I was able to have a second look on my private pc (also Ubuntu 20.04) where most things work as expected..
Then i realized I didn't enter my sublime license key on my work laptop.. so, i did this, restarted sublime and voila: it works! :)
So, now I'm just some minor issues (e.g. a scheduled task appears in the agenda on the scheduled date and time but also on every other day after that..).
I assume it's easier to open up single issues for that?
So i'd close this one, after one question: Do you have some kind of reference org-file to test "all/most" features?
Best, Daniel

**Comment by ihdavids** [comment]
Re scheduled tasks. Thats actually how they are supposed to operate. 

A single active timestamp means a one off appointment. 

Scheduled means starts here and continues till you mark it done. Deadline means it should be done at that point. 

Its poorly documented. I talk about it briefly in the todo tutorial i tried to cobble together:

https://github.com/ihdavids/orgextended_docs/blob/master/learning_todos.org

If you jump to the bit that reads: 

In the example I use the SCHEDULED marker. These are a powerful yet complicated part of org mode.

Its just after that.

The org manual talks about those here:
https://orgmode.org/manual/Deadlines-and-Scheduling.html

Like I say in our write up. I support SOME of the recurrance options (+1d etc) on timestamps but not all... one day.

**Comment by ihdavids** [comment]
There is the concept or recurring timestamps as well.

**Comment by ihdavids** [comment]
I do have some test org files. Some of them are hidden in the package, others are in the documentation. For instance unittest.org the table unit test can be found here: 

https://github.com/ihdavids/orgextended/blob/master/unittests.org

(Note the formulas are cropped from the web interpreted version of the file... so it loses something when seen there. There is a gif at the bottom of the tables documentation that shows the unit test running.)

It has most of the core table formula functionality built into a single document and executing all tables in the file reruns all the tests. That said it doesnt test and of the column row reordering, adding columns and rows or really any of that stuff. I havent come up with a good way to test that stuff yet. 

https://github.com/ihdavids/orgextended_docs/blob/master/tables.org

I am sllllooooooowwwwwwlllllyyyyy adding more docs to the system. But it is my least favorite activity and this is an R&R project for me. You are welcome to help me extend the docs! ;)

Some of the systems have their own internal tests like the duration and plist parsers.

I dont really have a suite yet and there are quite a few features. Some of the features are really hard to test effectively.

There are... a pretty big gamut of features at this point.

**Comment by ihdavids** [comment]
We dont support all of org mode and we deviate in some places but generally we are trying to sync with org. So the org mode docs kind of supplement ours where i have been unable to doc things.

**Comment by ihdavids** [comment]
Please feel free to open issues. I will respond where i can and fix what I can

**Comment by ihdavids** [comment]
All of the documentation is written as org files so you can grab any of it and work with that.

I am also adding one of my test files to the 1.2.3. Release.  Org Show Testfile will pop up a buffer from the plugin with a bunch of "stuff" 

Also if you run Org Show Worklog you will get a buffer full of my worklog since the initial release which has a bunch of features in it.

Note org mode is huge and the applications are pretty diverse, so no matter how big i make that test file it wont cover the half of it.

**Comment by ihdavids** [comment]
Did the above help?
Org Show Testfile is in 1.2.4. (I just pushed 1.2.5)

Where possible I am trying to do things the "org mode way"
 
https://orgmode.org

It really is a complex piece of tech.

It's a PIM
It's a task manager
it's a note taking system with refiling and capture tools.
it's a GTD management toolset.
it's a writers aid
it's a project planning tool
it's a document interchange format
it's a document authoring toolset
it's a presentation tool (Org Presentation mode or Export to Reveal.js come to mind here)
It's a personal wiki
it's a website authoring toolset
It's an in editor spreadsheet
It's a literate programming and reproducible research toolset (babel mode)
It's a self documenting IT aid
....

It really is hard to describe the gamut of tools and systems that surround org mode.
