### ISSUE TITLE
Customizable first day of week 

### ISSUE THREAD

**Issue by smithx** [ihdavids/orgextended#3]
Thank you so much, plugin is amazing!
Would you to make first day of week customizable ?

**Comment by ihdavids** [comment]
How would this work?
Can you give me a little more detail?

If it is easy enough I will happily extend this, but I am not entirely sure what you mean?
The agenda has a week view, a day view and a month view. Is your request to do with those?

The more detail you give me and the better chance I can implement what you are looking for here.

**Comment by smithx** [comment]
I mean calendar views, week view rendering...
Week starts with Monday and ends with Sunday, like at the picture:
![image](https://user-images.githubusercontent.com/2234320/105580252-53f86080-5d9c-11eb-83fb-78d90b5ee699.png)

**Comment by ihdavids** [comment]
Cool,
I haven't modified the month view yet but I have added some options to let you start the week view on monday. While I was at it I added an option to restrict the week view to a smaller range if you want.

![limit_week_view](https://user-images.githubusercontent.com/1059210/105614774-6fee0900-5d80-11eb-95a1-80154371196d.gif)

**Comment by ihdavids** [comment]
I will work on the month view if I can make time in the next little bit.

NOTE: The primary agenda view is customizable and some of the blocks have customization options of their own as well. I hope to let you write your own agenda blocks as well in the future, but I haven't had the time yet.

**Comment by ihdavids** [comment]
I may change how I am doing these options in the future. That week days restriction may make more sense as a block parameter on the week view....

**Comment by smithx** [comment]
Thank you, as it seems to me, choosing '0' as (default) value for Sunday will be inconvenient for cases as this:
https://github.com/ihdavids/orgextended/blob/master/orgdatepicker.py#L163
We will need conversions (except checks) to use it

**Comment by ihdavids** [comment]
Month view should now respect the agendaFirstDay.
I have changed agendaFirstDay to accept a string with the name of the day of the week or an integer.
Hope this helps.

**Comment by smithx** [comment]
Thanks,  I'm sorry but DatePicker Calendar view doesn't react on `agendaFirstDay` value

**Comment by ihdavids** [comment]
You mean the schedule dialog?
Yeah, I have not hooked that up. The option only impacts the agenda pane at the moment.

**Comment by ihdavids** [comment]
I suppose I can change the name option and make it impact that as well.

**Comment by ihdavids** [comment]
I have renamed the option firstDayOfWeek
Now the schedule, close and deadline date picker respect that option as well.

NOTE: I also renamed the main settings files from orgextended to OrgExtended. This was some feedback from my package review since it's viewed as "prettier" in the syntax status line to have CamelCase. 

This can be painful on windows boxes where case is finicky. You may have to blow away your clone and re-clone to get the case to be respected if you sync.

In addition, you may need to manually rename your settings file in your User folder. This is most painful because you will get a bunch of popups about syntax's/color schemes not be found. To avoid pain:

1) Close all org files before you do anything else.
2) Blow away your clone and re-clone.
3) rename your file in your User directory to be OrgExtended.sublime-settings rather than orgextended.sublime-settings
4) Now... restart sublime. That should get you functional with a minimum of pain.

**Comment by ihdavids** [comment]
There are now release notes in the messages folder. I have just posted the 1.0.2 tag which I think is the batch of changes required to get this to be functional as a package. So anything new will be going into 1.0.3 from now on.

**Comment by smithx** [comment]
Thank you very much
