### ISSUE TITLE
Clock records are not compatible with Emacs org-mode. 

### ISSUE THREAD

**Issue by jinie** [ihdavids/orgextended#41]
**Describe the bug**
Clock records are not compatible with Emacs org-mode. 
This may or may not be intentional, but limits interoperability between the two.

In orgextended, clock entries are stored in the PROPERTIES drawer, and the formatting is also different, i.e.

```
* TODO test item
:PROPERTIES:
  :CLOCK: [2021-05-28 fr 11:15]--[2021-05-28 fr 11:16] => 00:01
:END:
```
In emacs (27), a CLOCK entry is placed under the LOGBOOK drawer:

```
* DONE test item
  :LOGBOOK:
  CLOCK: [2021-05-27 to 14:58]--[2021-05-27 to 15:25] =>  0:27
  :END: 
```
Furthermore the actual CLOCK entry is prefixed by a colon, which is not the case in Emacs.

**To Reproduce**
1. Create a new TODO item and clock in.

**Expected behavior**
to ease interoperability, orgextended should be compatible with org-mode, which is especially important in a while orgextended is not fully self running.

**Platform:**
- PC ST4

**Comment by ihdavids** [comment]
Yup, fair enough.

Although... orgmode in emacs is really non standard itself on many of these types of things anyways. What is there is valid at the moment since the clock entries are just clock entries stored in valid property keys. You could do that in org (and I have, since I find it convenient to use the property API for accessing them.) 

We aren't compatible with emacs in many many ways at the moment, and likely will never be able to be for a large number of reasons, least of which is that we aren't running on a lisp REPL.

But I certainly hear your point in this item. I will make it configurable so you can choose. (although org lets you dump the clock entries as loose entries as well and I likely won't take the time to support that because I find that cluttered.)

Your preference for using a logbook drawer is fine, and I think I can now support it without to much effort anyways since I have a more generic drawer API than when I wrote the clocking stuff at this point.

**Comment by ihdavids** [comment]
1.2.33 should have this.
