### ISSUE TITLE
Request of list bullets as UTF-8 characters in org file

### ISSUE THREAD

**Issue by AlfredSAM** [ihdavids/orgextended#46]
Current org mode in Emacs seems to have smart, intelligent, and beautiful presentation of the list bullets, as well as the automatic adjustment of the size of fonts for different parts (e.g. fonts in the title are set to larger). Probably [here](https://github.com/sabof/org-bullets) is the example plugin, and [org mode in spacemacs](https://practical.li/spacemacs/org-mode/) can be another reference:

![image](https://user-images.githubusercontent.com/47268796/125157827-ab01be80-e19f-11eb-9720-509a9a496c80.png)

If the orgextended plugin in ST can also support such fancy style for editing org file, then the users would enjoy more fun. 

Thanks so much for this plugin!

**Comment by ihdavids** [comment]
Yup, aware of Org Bullets and other plugins that let you do that in emacs. I was and am still an avid emacs user on linux. Windows is where I tend to use sublime.

I wish I could give you that. I have asked for numerous features to be added to Sublime text that would allow me to do something like that.

The only thing I can think of is to build a font with Ligatures for ** and ***. While that would work, it's not something I have made time to try out. (Maybe someday)

If you can convince the sublime guys to give us:

- Mixed font support in a buffer
- Better overlay support.
- Narrowing like emacs

Then we might be able to offer some of those things. (Bullets, links that narrow elegantly, underlines under links, larger different font headers) I REALLY like this guys Org Mode setup. I find it really pretty:

https://www.youtube.com/watch?v=PMWwM8QJAtU
(Look at about 49 minute into the video to get some org mode glimpses during his presentation. He is using org-present so the presentation itself is just an org buffer treated as slides) He has a different config somewhere that uses a really nice blockier font for the headings that I find even prettier, but I can't seem to locate it at the moment. 
 
You will find requests for features like that in sublime on the forum, in the discord channels and on the sublime github repo. So far I have yet to get any traction on these requests. 

I wish I had a better answer for you. :(

If you have any suggestions on how this could be achieved in sublime, I would love to hear it.
The invisible stars was about as close as I could get without doing something buffer altering and yucky like this guy does:
https://marketplace.visualstudio.com/items?itemName=BobbyBoyd.vs-org

His plugin achieves that by dynamically replacing the stars with the bullet character and then stripping them on save. So far I have not felt like that was a good alternative, although, maybe, I will break down and do that at some point in the future. 

Right now that would break a TON of things though as the format of the file is dynamically parsed in various ways for various subsystems and it would need to take those special characters into account. It would give me a chance to fix some of the tech debt around parsing, but... I haven't been able to make the time.

There are other things I would rather fix first. Like getting us on python 3.8 vs the older 3.3... but that requires plugin dependency support at the moment and some upgrades to plugins I am depending on (like TableEditor that are currently in a non maintained state.... I may just consume them to do that, we will see)

Honestly the emacs community and plugin ecosystem is far more mature than the sublime version, I am hoping that as we look to Sublime Text 4 we will see the same growth in package interoperability. Emacs had the same problems that currently exist in sublime where A package can easily take you down and cause you to need to debug your setup. To a large degree it was through standardization and plugin authors learning to not re-invent the wheel and work together that much of that has improved. (it's still there, it's just less painful) I am hoping that the sublime crew will work to empower their community like that with essential features like package dependency support in ST4 sooner rather than later and work to help us work together to build more cohesive experiences like Spacemacs and Doom emacs. 

We will see what the future holds.

**Comment by AlfredSAM** [comment]
@ihdavids Thanks so much for your illustration and enthusiasm! Well, nowadays I also use spacemacs ONLY for org mode since the syntax and the design are both beautiful. However, for my coding works I mainly rely on neovim and ST, mainly because of their convenient setups for data science. As a user, I don't quite mind employing the merits of different tools to optimize the efficiency. Anyhow, I highly appreciate your works and just take your time. Thanks deeply again!
