### ISSUE TITLE
Extending the list of recognized URI schemes to handle, for example, [[airmail://message?mail=blah]]

### ISSUE THREAD

**Issue by zzaacchh** [ihdavids/orgextended#63]
Apologies if this is answered in the documentation somewhere -- I've searched and can't find exactly what I'm looking for.

I use MacOS, and I'd love orgextended to recognize airmail links, of the form [[airmail://message?mail=blah]].  These would open just find from the `open` shell command, so they don't need to be handled with any special processing -- just passed to `open`.  Would I need a custom resolver for this?

Thanks in advance!  Great package!

**Comment by ihdavids** [comment]
You would need to add to the resolvers.
It's been a bit since I worked on that part of the system. I honestly can't remember if I made it extensible in the User folder or not. I do not think so. It is one of the few pieces that remains from the original orgmode plugin I started extending.

You might be able to extend the prompt resolver with a custom setting, but I don't have a mac about to try it at the moment.
