### ISSUE TITLE
Question: BeanCounter Mode/Color Schemes

### ISSUE THREAD

**Issue by voltaireodactyl** [ihdavids/orgextended#66]
First off, thank you a million times for this beautiful plugin. I have the exact same struggle as you, constantly drawn back to emacs for OrgMode, but I truly love Sublime. So THANK YOU.

Question: Is there any downside to using the OrgBeanCounter mode as the syntax? Basically, for whatever reason, it seems to fit Org perfectly into my existing color theme (monokai pro), and I can't get the Color Generator to work so I keep going back to BeanCounter.

Just wanted to make sure I'm not going to blow something up this way. Thank you!

**Comment by ihdavids** [comment]
Nope, no downside.
The color generator should work, I would be interested in hearing what the problem is.

You should be able to switch to a color scheme you like (say ayu) and then run the generator in a buffer with it active. That should generate a new color scheme for you, it may require a sublime reload sometimes. If it's not working, I would like to hear what is problematic.

**Comment by voltaireodactyl** [comment]
Just closing this loop -- all is working as expected, my issue was not reading the instructions closely enough. I was trying to convert sublime-theme files rather than sublime-color-scheme files.  

That being said, BeanCounter seems to effortlessly adopt the color scheme from the sublime-theme files 🤷‍♂️

Either way, it's all working brilliantly, thank you again for the excellent plugin.

**Comment by ihdavids** [comment]
Great
Glad to hear it.
