### ISSUE TITLE
request: graph/mindmap view

### ISSUE THREAD

**Issue by berteh** [ihdavids/orgextended#68]
First of all thank you for you great plugin. It works just fine out of the box and provides wonderful features.

I particularly appreciate you integrating reveal.js export and inline images... and still need to explore backlinks and some more.

I'd find it useful to be able to *show an overview of the current ORG file as a clickable graph* of titles with relationships, both hierarchical, and -in another mode?- using their respective content links and backlinks.

Something inspired by https://tobloef.com/text2mindmap/  and https://kumu.io/  (check this last one it out if you don't know it: great free tool for system analysis and social networks research, alas not opensource).

Selecting nodes in this map would focus and open that node in the ORG text, and collapse the others. If too many nodes the map could have a "zoom" option filtering out all nodes but those with some relation to the current one (within a given depth). I'm available to discuss the feature if you like it

**Comment by ihdavids** [comment]
Interesting idea.
I need some more details to understand what you are trying to do so I can get a better understanding of what you might want to achieve here. You are also welcome to implement the feature and submit a PR if you have strong opinions of how it should behave.

Of note currently we have the following that each have some element of what I hear in your write up.

TODO Lists that filter todos across your notes in various ways. These are clickable and will take you there:
![image](https://user-images.githubusercontent.com/1059210/195395333-3d710cfc-66d2-4d46-a285-25ae12f9c962.png)

The agenda itself, also clickable and is based on the current state.
![image](https://user-images.githubusercontent.com/1059210/195405188-fdc36063-85a9-412e-bf76-6311bf9c794e.png)


#STARTUP: content 
That will auto fold the file when asked or when you save the file to just where your cursor is.
(Apparently I have not documented the startup file comment that well it behaves a little like global file heading cycling. It shows all headings as if you were looking at a table of contents but of course the current heading can't be folded because your cursor is there so that stays open. It can be a bit jarring to use, I really haven't found a wonderful balance for it but I use it myself quite often when editing worklogs.)
https://github.com/ihdavids/orgextended_docs/blob/master/learning_gantt_example.org
https://github.com/ihdavids/orgextended_docs/raw/master/images/global_tab_cycling.gif

Mermaid export and gnu plot export.
![image](https://user-images.githubusercontent.com/1059210/195396466-e967f660-3a6f-4289-9900-63346ce7d92c.png)
The example above uses gnu plot but I have done the same with mermaid js in more recent times when tracking a projects state:
https://github.com/ihdavids/orgextended_docs/blob/master/learning_gantt_example.org

Timesheet which is a new experimental thing I am working on that uses clocked data and effort estimates to build gantt charts using either mermaidjs or google gantt charts. (I haven't decided which offers the best option yet) It is a more automatic and batteries included version of the mermaid export above. NOTE the mermaid export above takes the data using a column block and exports the headings automatically to a table. That table is then pulled by an inline source block that exports a gnu plot file that is then converted to a gantt chart. Timesheet on the other hand just does all that in a timesheet specific fashion behind the scenes generating either a text table in your file or an independent gantt chart html or png.

https://github.com/ihdavids/orgextended/blob/master/messages/1.2.50.org#timechart-initial-experiment
https://github.com/ihdavids/orgextended/blob/master/messages/1.2.51.org#timesheet--timechart
![image](https://user-images.githubusercontent.com/1059210/195408557-108ed73d-8f36-493f-8e3a-cee56e5a91b9.png)


Also there is orgs, which is a go based org server that serves up access to your org mode data through a json rpc based websocket and offers command line and web based access to your org files. It's still REALLY in its infancy, I am just playing around with ideas right now. Ultimately I would like to remove the org DB from sublime and have the sublime plugin query orgs instead facilitating multiple different forms of access to your data and some more robust sync options as well. 
 
![image](https://user-images.githubusercontent.com/1059210/195398056-3859f743-cf3f-413b-91fe-478d6b268cef.png)
![image](https://user-images.githubusercontent.com/1059210/195410810-f65a018e-3e93-4c94-935a-754f9a4cf55b.png)


Anyways, all that to say, lots of various ways of looking at your data and I very much support extending that concept. That said I am not sure I understand your goals here. 
NOTE: Sublime does not offer any graphical capabilities itself so showing a graphical display like kumo or tobloef does isn't really possible within sublime. I could for instance offer the graphical display in the web version that orgs can serve up, but within sublime it would have to be text. So what does that look like?
Maybe it's just a mind map generated from a files headings using mermaid or dot? You mentioned clickable so I think that's not what you are looking for. Is it some kind of clickable image that I generate using some other tool? I don't think that's entirely possible with the mini html offered by sublime for phantoms today unless I pop up some other window that is not sublime, which would get us into cross platform problems (mac vs windows) unless its a web page but that offers other problems for linking back into sublime. Is it a text graph in a text buffer in sublime? That would be quite challenging to visualize and would it be easier to read than just a say folded view of the contents? This guy uses the file system and tree to do his mind mapping:
https://unixsheikh.com/tutorials/poor-mans-mind-mapping-tool-with-just-the-terminal.html

Is it just the headings without any content (like #+STARTUP:content)? If so is this in a special separate buffer to help you navigate the main content buffer?

(See 13:52 in the video he talks about a scrivener like view where he has headings on one side and the full document on the right) I have thought about doing something like that but I haven't had a huge need myself so it hasn't made the short list. 
https://www.youtube.com/watch?v=FtieBc3KptU

It is certainly not really a mind map though so I feel like I am missing your goal with that. 

Or jumping back to the image idea above, is this maybe completely external, a full mind map generated from your org document, editing the mind map would edit the org file and clicking on a link would pop up sublime with the text of the node? That could be done with orgs I suppose and a webpage.

Can you help me understand what you had in mind here. Text is a really poor way to discuss these things. I have a discord server I can send you a join link for if you would like to discuss this in more detail. I should really take the time and open it up as a public server for discussion about orgextended. I just didn't have the time to visit it that often so hadn't take the time to set that up.

NOTE: I tend to work on things that I know either I will use or I know someone else is actively going to use, so if you can frame it really well and describe how you want to use it and how it will really help your daily efforts, then I will be more likely to jump on it as I feel like I am helping you be more productive. 

Cheers

**Comment by berteh** [comment]
thanks for your detailled feedback. I'll read it quietly and come back soon with more infos.

**Comment by ihdavids** [comment]
Great.
Your other issue should be posting tonight in 1.2.52. Thanks for finding that.
