### ISSUE TITLE
"export to reveal js" fails on [[https:://target][named links]]

### ISSUE THREAD

**Issue by berteh** [ihdavids/orgextended#71]
When exporting an orgmode file to reveal JS, the output breaks on the first named link, such as `[[https:://target][named links]]`  and whatever followed is not exported... thus breaking the export.

tested on 1.2.52

**Comment by ihdavids** [comment]
Thanks for reporting this. I will take a look as soon as i can make time.
Ian

**Comment by ihdavids** [comment]
Looks like I need to improve my testing. 
This is the 3rd bug you have found and it's all me being sloppy and rushed when I made releases. Nice problem to have. 

The issue looks to be the same rust out I fixed in the html exporter, should have tested the reveal one as well.
When you report an issue, can you grab the callstack in the Ctrl + ` sublime console if there is one. Knowing the platform and callstack you are experiencing an issue on, that can really help expedite a fix for me and ensure I am looking at the same issue you are experiencing. 

note the link up there looks like it has an extra colon in it.

**Comment by ihdavids** [comment]
I just pushed 1.2.53, I am exporting with reveal js successfully with this release. Please let me know if you encounter any additional challenges.

**Comment by berteh** [comment]
confirmed fix, thanks.
will add callstack should I spot anything else.

**Comment by ihdavids** [comment]
Thanks for the confirmation and finding the bug.
