### ISSUE TITLE
manual installation without package control

### ISSUE THREAD

**Issue by ThaiDangFr** [ihdavids/orgextended#75]
hello
I would like to install orgextended without package control because I have restricted access. I tried to download the last tag and unzip it into the package directory but I have some errors. For other packages the method works. Is there any special things to do ?

**Comment by ihdavids** [comment]
Manual install isn't really supported but is possible I suppose.
This package uses the dependency mechanism for packages so needs some other packages to function.
It also manually installs one of the other table packages that I chose to build off of rather than re-invent the wheel on editing text tables.

**Comment by ihdavids** [comment]
The dependencies.json file lists the auto installed dependencies from package control
{
	"*": {
		"*": [
			"pathlib",
			"pyyaml",
			"dateutil",
			"requests",
			"regex",
			"websocket"
		]
	}
}

and we manually install the Table Editor package as welll during operation.

**Comment by ihdavids** [comment]
If you use the html export the system, if configured to do so, (it can also simply link to it) the system will pull highlightjs off a public CDN and embed it in your webpage if desired. Same goes for revealjs when building a presentation out of your org files.

I "think" that's everything I can think of that you would need to manage to install this manually.
